### PR TITLE
Fix SRC_URI in sigma-dut_git.bb recipe

### PR DESCRIPTION
**Pull request by drumilmahajan**
Update SRC_URI to use github instead of codeaurora as code aurora is end of its life

### CODE REVIEW

**Comment by drumilmahajan** [comment]
@thochstein Do the PRs automatically get reviewed by someone on this project or does it require that I tag one of the maintainers?

**Comment by thochstein** [comment]
Thanks @drumilmahajan. We had a slightly different change that I have cherry-picked. Please do `repo sync` and check that it works for you.

**Comment by drumilmahajan** [comment]
Ok perfect, will check that.. looks like it will work :) thank you

**Comment by thochstein** [comment]
Fixed similarly: https://github.com/nxp-imx/meta-imx/commit/b90902b834b0f390a597f1ba0b9b326cba7a2e66

**Pull request closed without merging**
