### PR TITLE
Fixed include version to match 4.6.0

### PR DESCRIPTION
**Pull request by matiop6**

### CODE REVIEW

**Comment by thochstein** [comment]
Hi @matiop6, thanks for the proposal. I want to make sure I understand your use case. We make these releases with a locked version of `meta-freescale`, and we don't see this issue. I assume you want to use a newer version of `meta-freescale`?

**Comment by matiop6** [comment]
Hi, dont know which version of  `meta-freescale` you used but ours `meta-freescale`  `commit 82cbf4e5adac1017adc1e4a2ce056c57b3148ba0 (HEAD, origin/kirkstone)` combined with [nxp-imx:kirkstone-5.15.71-2.2.0](https://github.com/nxp-imx/meta-imx/tree/kirkstone-5.15.71-2.2.0) caused compilation error (could not include opencv_4.5.2.imx.bb). Is it really necessary to include 4.5.2 in 4.6.0 recipe? In ours case it compiling well without it.

**Comment by thochstein** [comment]
Our release manifest uses a locked, older version of `meta-freescale` containing `opencv_4.5.2.imx.bb`. Your change would break our release.

I wanted to make sure I understood your use case. In later releases, we have gone away from such logic and do instead copy the upstream recipe locally. That way the recipe doesn't depend on `meta-freescale`.

Will try to produce a patch for you soon.

**Comment by thochstein** [comment]
Hi @matiop6. I've pushed a fix for your problem. Please do `repo sync` and give it a try.

**Comment by thochstein** [comment]
Fixed similarly: https://github.com/nxp-imx/meta-imx/commit/e219b910bb58f86dc34cbd6b76ae42bae8edbd77

**Pull request closed without merging**
