### PR TITLE
firmware-imx: Introduce IMX_USE_LINUX_FIRMWARE_SDMA to configure sdma FW sources.

### PR DESCRIPTION
**Pull request by Livius90**
Introduce `IMX_USE_LINUX_FIRMWARE_SDMA` to configure sdma FW sources.

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by thochstein** [comment]
Good idea, thanks!

**Review by MrCry0 — APPROVED** [review]

**Comment by Livius90** [comment]
@thochstein 
When it will be merged?

**Comment by thochstein** [comment]
Sorry for the delay!

**Comment by Livius90** [comment]
Please merge it to [scarthgap-6.6.23-2.0.0](https://github.com/nxp-imx/meta-imx/tree/scarthgap-6.6.23-2.0.0) also.

**Comment by thochstein** [comment]
Done

**Pull request merged**
