### PR TITLE
openssl: match bbappend only for 3.0 version

### PR DESCRIPTION
**Pull request by vj-kumar**
The patches carried by openssl bbappend is applicable only for openssl 3.0.x version. Modify the bbappend wildcard to match only 3.0.x releases.

### CODE REVIEW

**Comment by vj-kumar** [comment]
@thochstein @junzhuimx Can you please review this?

**Comment by thochstein** [comment]
Done, thank you @vj-kumar

**Comment by thochstein** [comment]
Hi @vj-kumar, can you please clarify the context where you had an issue? Were you building openssl 2.x?

**Comment by vj-kumar** [comment]
> Hi @vj-kumar, can you please clarify the context where you had an issue? Were you building openssl 2.x?

I was building openssl 1.1.1t

**Pull request merged**
